# Generated by Django 4.0 on 2021-12-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMedicalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='in_stock_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='qty_in_strip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='sell_price',
            field=models.IntegerField(),
        ),
    ]
