# Generated by Django 4.0 on 2021-12-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMedicalApp', '0002_alter_medicine_in_stock_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='company_is',
            new_name='company_id',
        ),
    ]
